name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ia codul din repo
      - uses: actions/checkout@v3

      # 2. Setează Java 17 (cerut de Android Gradle Plugin modern)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Instalează Gradle (folosește cea mai nouă versiune disponibilă)
      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      # 4. Rulează build-ul aplicației
      - name: Build with Gradle
        run: gradle build

      # 5. Salvează APK-ul ca artifact pentru descărcare
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LotoAClick-APK
          path: app/build/outputs/apk/debug/app-debug.apk
